#Sat Aug 02 08:44:31 UTC 2025


micronaut:
  application:
    name: nepaliBazar-backend

  server:
    cors:
      enabled: true
      configurations:
        web:
          allowed-origins:
            - "http://localhost:3000"
          allowed-methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          allowed-headers:
            - Authorization
            - Content-Type
            - Accept
          exposed-headers:
            - Authorization

  #  security:
  #    authentication: bearer
  #    token:
  #      jwt:
  #        signatures:
  #          secret:
  #            generator:
  #              secret: ${JWT_GENERATOR_SIGNATURE_SECRET}

  email:
    from:
      name: NepaliBazar Support
      email: sagardhungana06@gmail.com
    javamail:
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
            host: smtp.gmail.com
            port: 587
          transport:
            protocol: smtp
          debug: true

datasources:
  default:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
    url: jdbc:postgresql://localhost:5432/nepaliBazar
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    schema-generate: NONE
    maximum-pool-size: 10

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true

smtp:
  username: sagardhungana061@gmail.com
  password: srhw srgv axbz qmwi


